version: '3.8'

services:
  backend:
    container_name: example-book-store
    build:
      context: ./src/
    environment:
      - BookStore_ConnectionStrings_Catalog=Host=db:5432;Database=Catalog;Username=root;Password=root
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: on-failure
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookstore
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
